{
	'name': 'Travel',
	'description': 'Travel',
	'author': 'Kelompok A1',
	'depends': ['base','website','fleet'],
	'application': True,
	'data': ['views/travel_view.xml',
				'views/travel_menu.xml',
				'views/pool_view.xml',
				'views/schedule_view.xml',
				'views/web_template.xml',
				'security/ir.model.access.csv',
				'security/travel_access_rule.xml',
				'reports/travel_order_report.xml',
				'reports/travel_order_template.xml'],
}
